name: Require label

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, edited]

jobs:
  check-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      checks: write

    steps:
      - name: Check for label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = context.payload.pull_request.labels.map(l => l.name)
            const requiredLabel = "Test Label"

            if (!labels.includes(requiredLabel)) {
              core.setFailed(`❌ Missing required label: "${requiredLabel}"`)
            } else {
              core.info(`✅ Found required label: "${requiredLabel}"`)
            }